const fs = require('fs')
const base = '/Users/lsmbp/Documents/meds/components/Icon/'

fs.writeFileSync(base + 'Icon.jsx', [
  "import * as LucideIcons from 'lucide-react'",
  "",
  "function Icon({ name, size = 16, color = 'currentColor', strokeWidth = 1.5, ...props }) {",
  "  const PascalName = name",
  "    .split('-')",
  "    .map(part => part.charAt(0).toUpperCase() + part.slice(1))",
  "    .join('')",
  "",
  "  const LucideIcon = LucideIcons[PascalName]",
  "",
  "  if (!LucideIcon || typeof LucideIcon !== 'function') {",
  "    return (",
  "      <span style={{ display: 'inline-flex', width: size, height: size, alignItems: 'center', justifyContent: 'center', fontFamily: 'Geist, sans-serif', fontSize: 9, color: '#ec221f', border: '1px dashed #ec221f', borderRadius: 4 }}>",
  "        ?",
  "      </span>",
  "    )",
  "  }",
  "",
  "  return <LucideIcon size={size} color={color} strokeWidth={strokeWidth} {...props} />",
  "}",
  "",
  "export default Icon",
].join('\n'))

fs.writeFileSync(base + 'Icon.stories.js', [
  "import React, { useState } from 'react'",
  "import * as LucideIcons from 'lucide-react'",
  "import Icon from './Icon'",
  "",
  "export default {",
  "  title: 'Meddle DS/Icon',",
  "  component: Icon,",
  "  argTypes: {",
  "    name: { control: 'text' },",
  "    size: { control: 'select', options: [12, 16, 20, 24, 32] },",
  "    color: { control: 'color' },",
  "    strokeWidth: { control: { type: 'range', min: 0.5, max: 3, step: 0.25 } },",
  "  },",
  "}",
  "",
  "export const Default = {",
  "  args: { name: 'arrow-right', size: 16, color: '#1e1e1e', strokeWidth: 1.5 },",
  "}",
  "",
  "export const Sizes = {",
  "  name: 'Sizes',",
  "  render: () => (",
  "    <div style={{ display: 'flex', alignItems: 'center', gap: 24, padding: 32 }}>",
  "      {[12, 16, 20, 24, 32].map(size => (",
  "        <div key={size} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>",
  "          <Icon name='circle-user' size={size} color='#1e1e1e' />",
  "          <span style={{ fontFamily: 'Geist, sans-serif', fontSize: 11, color: '#757575' }}>{size}px</span>",
  "        </div>",
  "      ))}",
  "    </div>",
  "  ),",
  "}",
  "",
  "const toKebab = str => str.replace(/([A-Z])/g, m => '-' + m.toLowerCase()).replace(/^-/, '')",
  "",
  "const iconList = Object.entries(LucideIcons).filter(([key, val]) => {",
  "  return (",
  "    typeof val === 'function' &&",
  "    key !== 'createLucideIcon' &&",
  "    key !== 'default' &&",
  "    /^[A-Z]/.test(key)",
  "  )",
  "}).map(([key, Comp]) => ({ key, name: toKebab(key), Comp }))",
  "",
  "function AllIconsGrid() {",
  "  const [query, setQuery] = useState('')",
  "  const filtered = query ? iconList.filter(i => i.name.includes(query.toLowerCase())) : iconList",
  "  return (",
  "    <div style={{ padding: 32, fontFamily: 'Geist, sans-serif' }}>",
  "      <input",
  "        placeholder='Search icons...'",
  "        value={query}",
  "        onChange={e => setQuery(e.target.value)}",
  "        style={{ width: 240, padding: '8px 12px', borderRadius: 8, border: '1px solid #e6e6e6', fontFamily: 'Geist, sans-serif', fontSize: 14, marginBottom: 24, outline: 'none' }}",
  "      />",
  "      <div style={{ fontSize: 12, color: '#757575', marginBottom: 16 }}>{filtered.length} icons</div>",
  "      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>",
  "        {filtered.map(({ key, name, Comp }) => (",
  "          <div",
  "            key={key}",
  "            title={name}",
  "            style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, padding: '12px 8px', width: 80, borderRadius: 8, cursor: 'default', transition: 'background 0.1s' }}",
  "            onMouseEnter={e => e.currentTarget.style.backgroundColor = '#f0f7f8'}",
  "            onMouseLeave={e => e.currentTarget.style.backgroundColor = 'transparent'}",
  "          >",
  "            <Comp size={16} color='#1e1e1e' strokeWidth={1.5} />",
  "            <span style={{ fontFamily: 'Geist, sans-serif', fontSize: 9, color: '#757575', textAlign: 'center', wordBreak: 'break-all', lineHeight: 1.3 }}>{name}</span>",
  "          </div>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  )",
  "}",
  "",
  "export const AllIcons = {",
  "  name: 'All Icons',",
  "  render: () => <AllIconsGrid />,",
  "}",
].join('\n'))

console.log('Done — Icon fixed')
