const fs = require('fs')
const base = '/Users/lsmbp/Documents/meds/components/TokenReference/'

// ── ColourTokens.jsx ─────────────────────────────────────────────────────────

fs.writeFileSync(base + 'ColourTokens.jsx', [
  "import React from 'react'",
  "",
  "const FIGMA_LINK = 'https://www.figma.com/design/zMlxINZFLyMK6lD4o11aLd/MeDS?node-id=226-13679'",
  "",
  "const FigmaLink = ({ href }) => (",
  "  <a href={href} target='_blank' rel='noopener noreferrer' style={{ display: 'inline-block', marginBottom: 32, fontFamily: 'Geist, sans-serif', fontSize: 13, fontWeight: 500, color: '#005e70', textDecoration: 'none', borderBottom: '1px solid #005e70', paddingBottom: 2 }}>",
  "    View in Figma",
  "  </a>",
  ")",
  "",
  "const SectionTitle = ({ children }) => (",
  "  <h3 style={{ fontFamily: 'Geist, sans-serif', fontSize: 11, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#757575', margin: '32px 0 16px' }}>",
  "    {children}",
  "  </h3>",
  ")",
  "",
  "const Swatch = ({ name, value }) => (",
  "  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 8 }}>",
  "    <div style={{ width: 64, height: 64, borderRadius: 12, backgroundColor: value, border: '1px solid rgba(0,0,0,0.12)', boxShadow: '0 1px 4px rgba(12,12,13,0.1)' }} />",
  "    <div style={{ fontFamily: 'Geist, sans-serif' }}>",
  "      <div style={{ fontSize: 12, fontWeight: 500, color: '#1e1e1e' }}>{name}</div>",
  "      <div style={{ fontSize: 11, color: '#757575', marginTop: 2 }}>{value}</div>",
  "    </div>",
  "  </div>",
  ")",
  "",
  "const groups = {",
  "  Background: [",
  "    { name: 'default', value: '#ffffff' },",
  "    { name: 'default-hover', value: '#f5f5f5' },",
  "    { name: 'secondary', value: '#f5f5f5' },",
  "    { name: 'secondary-hover', value: '#e6e6e6' },",
  "    { name: 'tertiary', value: '#d9d9d9' },",
  "    { name: 'tertiary-hover', value: '#b3b3b3' },",
  "    { name: 'brand', value: '#005e70' },",
  "    { name: 'brand-light', value: '#f0f7f8' },",
  "    { name: 'positive', value: '#14ae5c' },",
  "    { name: 'danger', value: '#ec221f' },",
  "    { name: 'warning', value: '#e8b931' },",
  "    { name: 'disabled', value: '#d9d9d9' },",
  "  ],",
  "  Text: [",
  "    { name: 'primary', value: '#1e1e1e' },",
  "    { name: 'secondary', value: '#757575' },",
  "    { name: 'disabled', value: '#b3b3b3' },",
  "    { name: 'brand', value: '#005e70' },",
  "    { name: 'brand-secondary', value: '#003741' },",
  "    { name: 'on-brand', value: '#f0f7f8' },",
  "    { name: 'positive', value: '#14ae5c' },",
  "    { name: 'danger', value: '#ec221f' },",
  "    { name: 'warning', value: '#e8b931' },",
  "  ],",
  "  Border: [",
  "    { name: 'default', value: '#e6e6e6' },",
  "    { name: 'brand', value: '#005e70' },",
  "    { name: 'positive', value: '#14ae5c' },",
  "    { name: 'danger', value: '#ec221f' },",
  "    { name: 'warning', value: '#e8b931' },",
  "    { name: 'disabled', value: '#d9d9d9' },",
  "  ],",
  "  Icon: [",
  "    { name: 'primary', value: '#1e1e1e' },",
  "    { name: 'secondary', value: '#757575' },",
  "    { name: 'disabled', value: '#b3b3b3' },",
  "    { name: 'brand', value: '#005e70' },",
  "    { name: 'on-brand', value: '#f0f7f8' },",
  "    { name: 'positive', value: '#14ae5c' },",
  "    { name: 'danger', value: '#ec221f' },",
  "    { name: 'warning', value: '#e8b931' },",
  "  ],",
  "}",
  "",
  "function ColourTokens() {",
  "  return (",
  "    <div style={{ padding: 40, maxWidth: 960 }}>",
  "      <FigmaLink href={FIGMA_LINK} />",
  "      {Object.entries(groups).map(([title, tokens]) => (",
  "        <div key={title}>",
  "          <SectionTitle>{title}</SectionTitle>",
  "          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 24 }}>",
  "            {tokens.map(t => <Swatch key={t.name} {...t} />)}",
  "          </div>",
  "        </div>",
  "      ))}",
  "    </div>",
  "  )",
  "}",
  "",
  "export default ColourTokens",
].join('\n'))

// ── ColourTokens.stories.js ──────────────────────────────────────────────────

fs.writeFileSync(base + 'ColourTokens.stories.js', [
  "import ColourTokens from './ColourTokens'",
  "",
  "export default {",
  "  title: 'Meddle DS/Tokens/Colours',",
  "  component: ColourTokens,",
  "}",
  "",
  "export const AllColours = {",
  "  name: 'All Colours',",
  "  render: () => <ColourTokens />,",
  "}",
].join('\n'))

// ── SpacingTokens.jsx ────────────────────────────────────────────────────────

fs.writeFileSync(base + 'SpacingTokens.jsx', [
  "import React from 'react'",
  "",
  "const FIGMA_LINK = 'https://www.figma.com/design/zMlxINZFLyMK6lD4o11aLd/MeDS?node-id=226-13680'",
  "",
  "const FigmaLink = ({ href }) => (",
  "  <a href={href} target='_blank' rel='noopener noreferrer' style={{ display: 'inline-block', marginBottom: 32, fontFamily: 'Geist, sans-serif', fontSize: 13, fontWeight: 500, color: '#005e70', textDecoration: 'none', borderBottom: '1px solid #005e70', paddingBottom: 2 }}>",
  "    View in Figma",
  "  </a>",
  ")",
  "",
  "const SectionTitle = ({ children }) => (",
  "  <h3 style={{ fontFamily: 'Geist, sans-serif', fontSize: 11, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#757575', margin: '32px 0 16px' }}>",
  "    {children}",
  "  </h3>",
  ")",
  "",
  "const tokens = [",
  "  { name: 'Space 100', value: '4px' },",
  "  { name: 'Space 200', value: '8px' },",
  "  { name: 'Space 300', value: '12px' },",
  "  { name: 'Space 400', value: '16px' },",
  "  { name: 'Space 600', value: '24px' },",
  "  { name: 'Space 800', value: '32px' },",
  "  { name: 'Space 1000', value: '40px' },",
  "  { name: 'Space 1200', value: '48px' },",
  "  { name: 'Space 1600', value: '64px' },",
  "  { name: 'Space 2000', value: '80px' },",
  "  { name: 'Space 2400', value: '96px' },",
  "  { name: 'Space 4000', value: '160px' },",
  "]",
  "",
  "function SpacingTokens() {",
  "  return (",
  "    <div style={{ padding: 40, maxWidth: 960 }}>",
  "      <FigmaLink href={FIGMA_LINK} />",
  "      <SectionTitle>Spacing Scale</SectionTitle>",
  "      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>",
  "        {tokens.map(t => (",
  "          <div key={t.name} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>",
  "            <div style={{ width: 120, fontFamily: 'Geist, sans-serif', fontSize: 12, fontWeight: 500, color: '#1e1e1e', flexShrink: 0 }}>{t.name}</div>",
  "            <div style={{ height: 24, width: t.value, backgroundColor: '#005e70', borderRadius: 4, flexShrink: 0 }} />",
  "            <div style={{ fontFamily: 'Geist, sans-serif', fontSize: 11, color: '#757575' }}>{t.value}</div>",
  "          </div>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  )",
  "}",
  "",
  "export default SpacingTokens",
].join('\n'))

// ── SpacingTokens.stories.js ─────────────────────────────────────────────────

fs.writeFileSync(base + 'SpacingTokens.stories.js', [
  "import SpacingTokens from './SpacingTokens'",
  "",
  "export default {",
  "  title: 'Meddle DS/Tokens/Spacing',",
  "  component: SpacingTokens,",
  "}",
  "",
  "export const AllSpacing = {",
  "  name: 'All Spacing',",
  "  render: () => <SpacingTokens />,",
  "}",
].join('\n'))

// ── EffectTokens.jsx ─────────────────────────────────────────────────────────

fs.writeFileSync(base + 'EffectTokens.jsx', [
  "import React from 'react'",
  "",
  "const FIGMA_LINK = 'https://www.figma.com/design/zMlxINZFLyMK6lD4o11aLd/MeDS?node-id=226-13682'",
  "",
  "const FigmaLink = ({ href }) => (",
  "  <a href={href} target='_blank' rel='noopener noreferrer' style={{ display: 'inline-block', marginBottom: 32, fontFamily: 'Geist, sans-serif', fontSize: 13, fontWeight: 500, color: '#005e70', textDecoration: 'none', borderBottom: '1px solid #005e70', paddingBottom: 2 }}>",
  "    View in Figma",
  "  </a>",
  ")",
  "",
  "const SectionTitle = ({ children }) => (",
  "  <h3 style={{ fontFamily: 'Geist, sans-serif', fontSize: 11, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#757575', margin: '32px 0 16px' }}>",
  "    {children}",
  "  </h3>",
  ")",
  "",
  "const TokenLabel = ({ name, value }) => (",
  "  <div style={{ fontFamily: 'Geist, sans-serif', marginTop: 8 }}>",
  "    <div style={{ fontSize: 12, fontWeight: 500, color: '#1e1e1e' }}>{name}</div>",
  "    <div style={{ fontSize: 11, color: '#757575', marginTop: 2 }}>{value}</div>",
  "  </div>",
  ")",
  "",
  "const shadows = [",
  "  { name: 'Shadow 100', value: '0 1px 2px rgba(12,12,13,0.05)' },",
  "  { name: 'Shadow 200', value: '0 1px 4px rgba(12,12,13,0.1)' },",
  "  { name: 'Shadow 300', value: '0 2px 8px rgba(12,12,13,0.12)' },",
  "  { name: 'Shadow 400', value: '0 4px 16px rgba(12,12,13,0.12)' },",
  "  { name: 'Shadow 500', value: '0 8px 24px rgba(12,12,13,0.12)' },",
  "  { name: 'Shadow 600', value: '0 16px 40px rgba(12,12,13,0.16)' },",
  "]",
  "",
  "const overlays = [",
  "  { name: 'Overlay', bg: 'rgba(0,0,0,0.5)' },",
  "  { name: 'Blanket', bg: 'rgba(0,0,0,0.8)' },",
  "  { name: 'Layer', bg: 'rgba(255,255,255,0.08)' },",
  "  { name: 'Glass', bg: 'rgba(255,255,255,0.12)', blur: true },",
  "]",
  "",
  "function EffectTokens() {",
  "  return (",
  "    <div style={{ padding: 40, maxWidth: 960 }}>",
  "      <FigmaLink href={FIGMA_LINK} />",
  "      <SectionTitle>Shadows</SectionTitle>",
  "      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 32 }}>",
  "        {shadows.map(s => (",
  "          <div key={s.name} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>",
  "            <div style={{ width: 80, height: 80, borderRadius: 12, backgroundColor: '#ffffff', boxShadow: s.value, border: '1px solid #f0f0f0' }} />",
  "            <TokenLabel name={s.name} value={s.value} />",
  "          </div>",
  "        ))}",
  "      </div>",
  "      <SectionTitle>Overlays</SectionTitle>",
  "      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 32 }}>",
  "        {overlays.map(o => (",
  "          <div key={o.name} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>",
  "            <div style={{ width: 80, height: 80, borderRadius: 12, backgroundColor: o.bg, backdropFilter: o.blur ? 'blur(12px)' : 'none', border: '1px solid rgba(255,255,255,0.2)' }} />",
  "            <TokenLabel name={o.name} value={o.bg} />",
  "          </div>",
  "        ))}",
  "      </div>",
  "    </div>",
  "  )",
  "}",
  "",
  "export default EffectTokens",
].join('\n'))

// ── EffectTokens.stories.js ──────────────────────────────────────────────────

fs.writeFileSync(base + 'EffectTokens.stories.js', [
  "import EffectTokens from './EffectTokens'",
  "",
  "export default {",
  "  title: 'Meddle DS/Tokens/Effects',",
  "  component: EffectTokens,",
  "}",
  "",
  "export const AllEffects = {",
  "  name: 'All Effects',",
  "  render: () => <EffectTokens />,",
  "}",
].join('\n'))

console.log('Done — ColourTokens, SpacingTokens, EffectTokens written')
